[package]
name = "habitat_butterfly"
version = "0.1.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "build.rs"
workspace = "../../"

[[bin]]
name = "butterfly"
path = "src/main.rs"
doc = false

[dependencies]
byteorder = "*"
bytes = "*"
chrono = "*"
env_logger = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git" }
habitat_common = { path = "../common" }
log = "*"
lazy_static = "*"
prometheus = "*"
prost = "*"
prost-derive = "*"
rand = "*"
serde = { version = "*", features = ["rc"] }
serde_derive = "*"
serde_json = "*"
tempfile = "*"
time = "*"
threadpool = "*"
toml = { version = "*", default-features = false }
uuid = { version = "*", features = ["v4"] }
zmq = { git = "https://github.com/erickt/rust-zmq", branch = "release/v0.8" }

[dev-dependencies]
habitat_butterfly_test = { path = "../butterfly-test" }
mktemp = "*"

[build-dependencies]
heck = "*"
pkg-config = "*"
prost = "*"
prost-build = "*"
tempfile = "*"

[features]
default = ["protocols"]
protocols = []
ignore_inconsistent_tests = []
